message-push:
  git_url: https://github.com/opensourceways/message-push.git
  pipeline_url: https://devcloud.cn-north-4.huaweicloud.com/cicd/project/3a76c1785dda4b13a399937d1978f240/pipeline/history/ea5489fc52984d36a1b33fc6378ddb85?from=out-project&v=1
  endpoint_id: a00c8423f08b4f2fb68c72bd739d4f48
  owener: shishupei

BigFiles:
  git_url: https://github.com/opensourceways/BigFiles.git
  pipeline_url: https://devcloud.cn-north-4.huaweicloud.com/cicd/project/3a76c1785dda4b13a399937d1978f240/pipeline/history/58d2a62564c14ce1815dcce4d1064020?from=in-project&v=1
  endpoint_id: 213f55413c51481da30769de540a5577
  owner: jufangqun,zhouyi

certification-server:
  git_url: https://github.com/opensourceways/certification-server.git
  pipeline_url: https://devcloud.cn-north-4.huaweicloud.com/cicd/project/3a76c1785dda4b13a399937d1978f240/pipeline/history/128c1a12cee14cd3ae4059676f9c3c61?from=out-project&v=1
  endpoint_id: 8c4ad6369c294b33865f286154e64605
  owner: zhaoyan    

message-manager:
  git_url:
  pipeline_url:
  endpoint_id:
  owner:

EasySoftwareService:
  git_url: https://github.com/opensourceways/EasySoftwareService.git
  pipeline_url: https://devcloud.cn-north-4.huaweicloud.com/cicd/project/3a76c1785dda4b13a399937d1978f240/pipeline/history/99c7d59e96c74d5c963cbf39a9049518?from=in-project&v=1
  endpoint_id: 582a9b18ea9e4d8993b4461761d3f1d3
  owener: xiechengzhi

EasySoftwareInput:
  git_url: https://github.com/opensourceways/EasySoftwareInput.git
  pipeline_url: https://devcloud.cn-north-4.huaweicloud.com/cicd/project/3a76c1785dda4b13a399937d1978f240/pipeline/history/704fc4f23f8a43efaa7a470bbb0b99ec?from=in-project&v=1
  endpoint_id: ba94ad848e4f4fe399650626298f0f74
  owener: gouzhonglin

easysoftware-autoupgrade:
  git_url: https://github.com/opensourceways/easysoftware-autoupgrade.git
  pipeline_url: https://devcloud.cn-north-4.huaweicloud.com/cicd/project/3a76c1785dda4b13a399937d1978f240/pipeline/history/dfffe2767c914e96aa7e7ae294ba567c?from=in-project&v=1
  endpoint_id: 94d7a318bf27475291fde12d4e2fc4e2
  owener: lifan


